dev-cmd/update-license-data: Fix "undefined variable `latest tag`"
- This was broken by some refactoring in https://github.com/Homebrew/brew/pull/8215.
- I noticed that the Actions runs for the scheduled task had a funny way
  of succeeding:

```
==> Updating SPDX license data...
==> git add
Error: undefined local variable or method `latest_tag' for Homebrew:Module
Please report this issue:
==> git commit
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/update-license-data.rb:38:in `update_license_data'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:112:in `<main>'
```