cmd/list.rb: fix `brew ls` in verbose mode"
When `HOMEBREW_VERBOSE` is set, `brew ls` passes `-v` and `--verbose`
arguments to the system's `ls` command. This fails with:

```
ls: illegal option -- -

usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]

Error: Failure while executing; ls -v --verbose /Users/username/homebrew/Cellar exited with 1.
```

To circumvent this issue, we filter out `-v` and `--verbose` flags from the list of flags passed to `ls`.

Signed-off-by: Maxim Belkin <maxim.belkin@gmail.com>