Use `git tag -l` instead of `git tag --list`
- In early versions of git (~1.7), the `list` flag doesn't exist and
  causes the brew update on install to error:

```
Error: Failure while executing; `git config --local --replace-all homebrew.private false` exited with 129.
error: unknown option `list'
```

- The shortened `-l` flag exists in all versions, though, so switch to
  that.
- This was reported in Linuxbrew/install issue 78.